---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminfrontend
  namespace: surfer-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin_frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin_frontend
        app: surfer-store
        name: adminfrontend
        role: adminfrontend
        tier: client
    spec:
      containers:
        - name: adminfrontend
          image: k8tan/admin_frontend
          imagePullPolicy: Always
          ports:
            - name: adminfrontend
              containerPort: 3000
