---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartdb
  labels:
    name: cartdb
  namespace: surfer-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cartdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cartdb
        app: surfer-store
        name: cartdb
        role: mysql
        tier: db
    spec:
      containers:
        - name: cartdb
          image: k8tan/cart_db
          imagePullPolicy: Always
          ports:
            - name: mysql
              containerPort: 3306

