---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
  namespace: frothly-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: productservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: productservice
        app: frothly-store
        name: productservice
        role: productservice
        tier: middleware
    spec:
      containers:
        - name: productservice
          image: k8tan/product_microservice
          imagePullPolicy: Always
          ports:
            - name: productservice
              containerPort: 6767
