---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdb
  labels:
    name: productdb
  namespace: surfer-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: productdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: productdb
        app: surfer-store
        name: productdb
        role: mysql
        tier: db
    spec:
      containers:
        - name: productdb
          #image: k8tan/product_db
          image: k8tan/product_db:latest
          imagePullPolicy: Always
          ports:
            - name: mysql
              containerPort: 3306

