---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfrontend
  namespace: frothly-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webfrontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webfrontend
        app: frothly-store
        name: webfrontend
        role: webfrontend
        tier: client
    spec:
      containers:
        - name: webfrontend
          image: timfrazier1/web_frontend
          imagePullPolicy: Always
          ports:
            - name: webfrontend
              containerPort: 8088

